CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE event(
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    img_url VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    REMOTE BOOLEAN NOT NULL,
    date TIMESTAMP NOT NULL,
);
